// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/change-password" | "/dashboard" | "/dashboard/admin/agreements" | "/dashboard/admin/donations" | "/dashboard/admin/forms" | "/dashboard/admin/parameters" | "/dashboard/admin/tenants" | "/dashboard/admin/tenants/new" | "/dashboard/admin/users" | "/dashboard/applications" | "/dashboard/applications/[id]" | "/dashboard/applications/[id]/payments" | "/dashboard/applications/[id]/references" | "/dashboard/applications/new" | "/dashboard/change-password" | "/dashboard/funds" | "/dashboard/funds/[id]" | "/dashboard/funds/[id]/overview" | "/dashboard/funds/[id]/payment" | "/dashboard/funds/[id]/students" | "/dashboard/funds/[id]/students/[applicationId]/payments" | "/dashboard/funds/flow" | "/dashboard/funds/new" | "/dashboard/home" | "/dashboard/invitations" | "/dashboard/invitations/reference/[id]" | "/dashboard/payments" | "/dashboard/payments/history" | "/dashboard/payments/upcoming" | "/dashboard/pool" | "/dashboard/references" | "/dashboard/settings" | "/dashboard/settings/about" | "/dashboard/settings/contracts" | "/dashboard/settings/notifications" | "/dashboard/settings/password" | "/dashboard/settings/permissions" | "/forgot-password" | "/health" | "/login" | "/onboarding" | "/register" | "/unauthorized"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/debug/sync-db" | "/api/donations" | "/api/seed-payments" | "/api/send-email" | "/api/upload" | "/api/webhooks/payment-complete"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/dashboard/payments"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/debug/sync-db": {}
  "/api/donations": {}
  "/api/seed-payments": {}
  "/api/send-email": {}
  "/api/upload": {}
  "/api/webhooks/payment-complete": {}
  "/change-password": {}
  "/dashboard": {}
  "/dashboard/admin/agreements": {}
  "/dashboard/admin/donations": {}
  "/dashboard/admin/forms": {}
  "/dashboard/admin/parameters": {}
  "/dashboard/admin/tenants": {}
  "/dashboard/admin/tenants/new": {}
  "/dashboard/admin/users": {}
  "/dashboard/applications": {}
  "/dashboard/applications/[id]": { "id": string; }
  "/dashboard/applications/[id]/payments": { "id": string; }
  "/dashboard/applications/[id]/references": { "id": string; }
  "/dashboard/applications/new": {}
  "/dashboard/change-password": {}
  "/dashboard/funds": {}
  "/dashboard/funds/[id]": { "id": string; }
  "/dashboard/funds/[id]/overview": { "id": string; }
  "/dashboard/funds/[id]/payment": { "id": string; }
  "/dashboard/funds/[id]/students": { "id": string; }
  "/dashboard/funds/[id]/students/[applicationId]/payments": { "id": string; "applicationId": string; }
  "/dashboard/funds/flow": {}
  "/dashboard/funds/new": {}
  "/dashboard/home": {}
  "/dashboard/invitations": {}
  "/dashboard/invitations/reference/[id]": { "id": string; }
  "/dashboard/payments": {}
  "/dashboard/payments/history": {}
  "/dashboard/payments/upcoming": {}
  "/dashboard/pool": {}
  "/dashboard/references": {}
  "/dashboard/settings": {}
  "/dashboard/settings/about": {}
  "/dashboard/settings/contracts": {}
  "/dashboard/settings/notifications": {}
  "/dashboard/settings/password": {}
  "/dashboard/settings/permissions": {}
  "/forgot-password": {}
  "/health": {}
  "/login": {}
  "/onboarding": {}
  "/register": {}
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/dashboard/payments": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
