// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/change-password">> = Specific
  const handler = {} as typeof import("../../../app/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/admin/agreements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/agreements">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/admin/agreements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/admin/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/forms">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/admin/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/admin/parameters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/parameters">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/admin/parameters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/admin/tenants/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/tenants/new">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/admin/tenants/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/admin/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/tenants">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/admin/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications/[id]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/[id]/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications/[id]/payments">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/[id]/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/[id]/references/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications/[id]/references">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/[id]/references/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications/new">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/change-password">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds/[id]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/[id]/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds/[id]/payment">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/[id]/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/[id]/students/[applicationId]/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds/[id]/students/[applicationId]/payments">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/[id]/students/[applicationId]/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/[id]/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds/[id]/students">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/[id]/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds/new">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/funds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/funds">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/funds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/home">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/invitations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invitations">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/invitations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/invitations/reference/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invitations/reference/[id]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/invitations/reference/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/payments/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments/history">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/payments/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/payments/upcoming/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments/upcoming">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/payments/upcoming/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/pool/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pool">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/pool/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/references/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/references">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/references/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/about">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/contracts">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/notifications">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/password">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/permissions">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../../app/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/sync-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/sync-db">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/sync-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seed-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-payments">> = Specific
  const handler = {} as typeof import("../../../app/api/seed-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-email">> = Specific
  const handler = {} as typeof import("../../../app/api/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/payments/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/payments/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
