var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/forms/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_5ea421b7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b46040fc._.js")
R.c("server/chunks/ssr/node_modules_e2d1c5df._.js")
R.c("server/chunks/ssr/[externals]__e8a2741f._.js")
R.c("server/chunks/ssr/app_d82f1d46._.js")
R.c("server/chunks/ssr/app_1c6c0c3f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/node_modules_next_c119b278._.js")
R.c("server/chunks/ssr/node_modules_@auth_core_e00e322b._.js")
R.c("server/chunks/ssr/node_modules_jose_dist_webapi_f15cbee2._.js")
R.c("server/chunks/ssr/node_modules_zod_v4_34378348._.js")
R.c("server/chunks/ssr/node_modules_drizzle-orm_fa377308._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3021efa3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fb8b9cce._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_drizzle-orm_index_daf5b681.js")
R.c("server/chunks/ssr/node_modules_80c1e725._.js")
R.c("server/chunks/ssr/_bfd9f02c._.js")
R.c("server/chunks/ssr/node_modules_783be535._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ad847b._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/dashboard/admin/forms/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/app/icon.jpg.mjs { IMAGE => \\\"[project]/app/icon.jpg (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", METADATA_1 => \"[project]/app/apple-icon.png.mjs { IMAGE => \\\"[project]/app/apple-icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/app/dashboard/admin/forms/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/dashboard/admin/forms/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/app/icon.jpg.mjs { IMAGE => \\\"[project]/app/icon.jpg (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", METADATA_1 => \"[project]/app/apple-icon.png.mjs { IMAGE => \\\"[project]/app/apple-icon.png (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/app/dashboard/admin/forms/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
